/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: message.proto */

#ifndef PROTOBUF_C_message_2eproto__INCLUDED
#define PROTOBUF_C_message_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1005000 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct SerializedUser SerializedUser;


/* --- enums --- */


/* --- messages --- */

struct  SerializedUser
{
  ProtobufCMessage base;
  int32_t id;
  char *username;
};
#define SERIALIZED_USER__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&serialized_user__descriptor) \
    , 0, (char *)protobuf_c_empty_string }


/* SerializedUser methods */
void   serialized_user__init
                     (SerializedUser         *message);
size_t serialized_user__get_packed_size
                     (const SerializedUser   *message);
size_t serialized_user__pack
                     (const SerializedUser   *message,
                      uint8_t             *out);
size_t serialized_user__pack_to_buffer
                     (const SerializedUser   *message,
                      ProtobufCBuffer     *buffer);
SerializedUser *
       serialized_user__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   serialized_user__free_unpacked
                     (SerializedUser *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*SerializedUser_Closure)
                 (const SerializedUser *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor serialized_user__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_message_2eproto__INCLUDED */
