/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: message.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "message.pb-c.h"
void   serialized_user__init
                     (SerializedUser         *message)
{
  static const SerializedUser init_value = SERIALIZED_USER__INIT;
  *message = init_value;
}
size_t serialized_user__get_packed_size
                     (const SerializedUser *message)
{
  assert(message->base.descriptor == &serialized_user__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t serialized_user__pack
                     (const SerializedUser *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &serialized_user__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t serialized_user__pack_to_buffer
                     (const SerializedUser *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &serialized_user__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
SerializedUser *
       serialized_user__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (SerializedUser *)
     protobuf_c_message_unpack (&serialized_user__descriptor,
                                allocator, len, data);
}
void   serialized_user__free_unpacked
                     (SerializedUser *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &serialized_user__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor serialized_user__field_descriptors[2] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(SerializedUser, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "username",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(SerializedUser, username),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned serialized_user__field_indices_by_name[] = {
  0,   /* field[0] = id */
  1,   /* field[1] = username */
};
static const ProtobufCIntRange serialized_user__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor serialized_user__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "SerializedUser",
  "SerializedUser",
  "SerializedUser",
  "",
  sizeof(SerializedUser),
  2,
  serialized_user__field_descriptors,
  serialized_user__field_indices_by_name,
  1,  serialized_user__number_ranges,
  (ProtobufCMessageInit) serialized_user__init,
  NULL,NULL,NULL    /* reserved[123] */
};
